### ISSUE TITLE
Modify Subjects page BE

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/openstax-cms#1031]
# Description

To construct the context menu for the books on the Subjects page, the front end will need the book cover color and whether there are instructor resources and student resources. Ideally, three fields would be added to the `pages/subjects` data:
```
cover_color
has_faculty_resources
has_student_resources
```

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
