### ISSUE TITLE
Upgrade to Wagtail 2.15.x

### ISSUE THREAD

**Issue by mwharrison** [openstax/openstax-cms#1223]
# Description
Wagtail has release a new version.

Here are the release notes: https://docs.wagtail.io/en/stable/releases/2.15.html
Be sure to look at the [upgrade considerations](https://docs.wagtail.io/en/stable/releases/2.15.html#upgrade-considerations)!

Be sure to upgrade to the latest 2.15.x version (as of now, it's 2.15.1)

# Acceptance Criteria
- Wagtail is upgraded 

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Approvals
1A-DEFINE
- [ ] PDM approves UX LoFi Design

1C-DESIGN
  - [ ] PDM approves UX HiFi Design

4A-UX REV
  - [ ] UX approves change
  - [ ] PDM approves change

# Process 
[Work Management for BIT](https://github.com/openstax/business-intel/blob/master/CONTRIBUTING.md)

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
