### ISSUE TITLE
Try setting up Wagtail to auto-convert images to WEBP

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/openstax-cms#1234]
# Description
Wagtail has the ability to auto-convert uploaded images. By default, it was set up to convert WEBP to PNG. We changed that. WEBP is the preferred format. If possible, configure Wagtail to convert uploaded PNG and JPG files to WEBP.

This should help with the problem we have of very large PNGs and (sometimes) JPGs.

**Comment by brittanyearly** [comment]
Verified in Staging. Image is uploaded and keeps the .png or .jpg, but upon download, image is .webp.

**Comment by brittanyearly** [comment]
Verified in Production.
