### ISSUE TITLE
webinar search is broken

### ISSUE THREAD

**Issue by richtier** [openstax/openstax-cms#1246]
webinar search http://localhost:8000/admin/webinars/webinar/?q=foo results in 

![image](https://user-images.githubusercontent.com/5485798/149574134-abf674bc-ab94-4801-87ab-92b5b0e9a11e.png)

`Cannot resolve keyword 't' into field. Choices are: description, display_on_tutor_page, end, id, registration_link_text, registration_url, spaces_remaining, speakers, start, title`

I think it's because of this https://github.com/openstax/openstax-cms/issues/1238

explained [here](https://codereview.doctor/features/python/best-practice/tuple-missing-trailing-comma)

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
