### ISSUE TITLE
Switch Django admin to read the SSO cookie vs using OAuth flow

### ISSUE THREAD

**Issue by mwvolo** [openstax/openstax-cms#1294]
# Description
The Django admin is using the oauth flow for authenticating admins in the CMS. 
The FE is already using the SSO cookie, so we really don't need to keep the oauth flow for login. This also moves us towards a centralized authentication and authorization system.

Future work will allow more fine grained controls. For now, users will need to be added manually or login and given the correct permissions if they should not have full administrative access on accounts and the CMS.

# Acceptance Criteria
- [ ] A user should be able to login to /admin when assigned is_administrator in accounts

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
