### ISSUE TITLE
Update robots.txt

### ISSUE THREAD

**Issue by edwoodward** [openstax/openstax-cms#1304]
### Description
Robots.txt appears to live in an [S3 bucket](https://s3.console.aws.amazon.com/s3/object/unified-web-primary?region=us-east-2&prefix=robots/prod/robots.txt). Google is indexing the `api/spike` pages, so adding the entire URL might help prevent that.

The line
`/api/spike`

should be updated to
`/apps/cms/api/spike`

### Acceptance Criteria

openstax.org/robots.txt should contain `/apps/cms/api/spike`

**Comment by mwvolo** [comment]
@edwoodward will check with Dante on this

**Comment by edwoodward** [comment]
@Dantemss updated the file in the S3 bucket

**Comment by mwvolo** [comment]
Ed verified - on production
