### ISSUE TITLE
Remove unused pages from Pages model

### ISSUE THREAD

**Issue by edwoodward** [openstax/openstax-cms#1305]
### Description

The following pages are no longer is use as far as I can tell and could be removed from the Pages model.
* Higher Education - slug: higher-education
* Give - slug: give
* AP - slug: ap
* Support - slug: support
* Comp Copy - slug: comp-copy
* Adopt Form - slug: adoption-form
* Interest Form - slug: interest-form
* Hero Journey Page - not on production
* Math Quiz Page - slug: quiz-results
* LLPH Page - slug: llph
* Tutor Landing - not on production

This list needs to be verified by others. I could be very wrong.

### Acceptance Test

**Before deployment of code, delete these pages from the CMS. Failing to do so will make deleting them difficult after code release**
* Higher Education
* AP
* Support
* Comp Copy
* Adopt Form
* Interest Form
* Hero Journey Page
* Tutor Landing

These pages are no longer available for creation in the CMS

**Comment by mwvolo** [comment]
@daninicholson @isabellahsiao96 
Can you all help in letting us know if some of these pages are still needed on the website?

**Comment by daninicholson** [comment]
Higher Education - slug: higher-education - **delete**
Give - slug: give - **keep**
AP - slug: ap - **delete**
Support - slug: support - **delete**
Comp Copy - slug: comp-copy - **delete**
Adopt Form - slug: adoption-form **delete**
Interest Form - slug: interest-form **delete** 
Hero Journey Page - not on production what does this mean? @edwoodward 
Math Quiz Page - slug: quiz-results **keep**
LLPH Page - slug: llph **keep**
Tutor Landing - not on production ??

@ltjosephs Could you verify that the pages where I said "delete" above don't have any content on them?

**Comment by edwoodward** [comment]
@daninicholson It means the page is not in use on production. It either was never used or has already been removed.

**Comment by ltjosephs** [comment]
@daninicholson 

- **Higher Education - slug: higher-education - delete:** No content
- **AP - slug: ap - delete:** No content
- **Support - slug: support - delete:** No content
- **Comp Copy - slug: comp-copy - delete:** No content
- **Adopt Form - slug: adoption-form delete:** No content
- **Interest Form - slug: interest-form delete:** No content

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
