### ISSUE TITLE
Handle review that does not have a partner

### ISSUE THREAD

**Issue by edwoodward** [openstax/openstax-cms#1315]
### Description
An error happened on production when a review did not have a partner and the sync_reviews command failed because of it. The error happened when getting the `partner_sf_account_id` from the review partner object. The error was reported in [Sentry](https://sentry.io/organizations/openstax/issues/3263772192/?project=5594444)

### Acceptance Testing
Reviews without a Partner will be skipped and deleted when preparing data to be sent to Salesforce. This is nearly impossible to test.

**Comment by brittanyearly** [comment]
Nothing to test in QA.

**Comment by brittanyearly** [comment]
Nothing to test in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
