### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by edwoodward** [openstax/openstax-cms#1319]
### Description
The documentation in the docs directory has not been updated is a long time. Apps have been added and removed since the last update. The doc should cover the latest apps in the CMS and the database schema image should be updated.

Link to docs: https://github.com/openstax/openstax-cms/tree/main/docs
Link to wiki: https://github.com/openstax/openstax-cms/wiki

### Acceptance Criteria
* Doc markdown file is updated
* database schema file is updated

**Comment by mwvolo** [comment]
verify if allies are still needed

**Comment by mwvolo** [comment]
@brittanyearly will move the documentation to confluence
