### ISSUE TITLE
Subject search for blog not working on dev

### ISSUE THREAD

**Issue by edwoodward** [openstax/openstax-cms#1330]
### Description
The data structure of the json stored for subjects on dev is different than it was during local development. The original structure was 
`[{'type': 'subject', 'value': [{'subject': 4}], 'id': '98a80440-8b7c-4857-89ee-7bebbc87b904'}]`

The structure on dev is
`[{'type': 'subject', 'value': [{'type': 'item', 'value': {'subject': 1, 'featured': False}, 'id': '78e7e9c1-487f-42bb-b960-4a2901aa3150'}]`

The code needs to work with the structure on dev. Blog Collections and content types have the same issue.

### Acceptance Test
 - subject search for blog posts works - https://dev.openstax.org/apps/cms/api/search/?subjects=Math

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
