### ISSUE TITLE
Search feature not functioning 

### ISSUE THREAD

**Issue by yblock** [openstax/openstax-cms#1331]
The search field on the main page of wagtail and the search feature to select snippets on pages (and maybe others) is not currently functioning. 

![Screen Shot 2022-08-04 at 10.53.38 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/4a45827e-0444-4983-8696-ed0cac0997f2)

**Comment by brittanyearly** [comment]
Verified in Production.
