### ISSUE TITLE
Upgrade to Wagtail 4.04

### ISSUE THREAD

**Issue by mwvolo** [openstax/openstax-cms#1343]
We are currently on Wagtail 3.0.3 - the current stable version is 4.2.0. However, Wagtail recommends updates happen on feature release numbers, so we would update to 4.0.4, then 4.1.2 and finally to 4.2.0. Other cards will be created for the other 2 upgrades. This update will include an update to Django 4.1.7 which is the current stable release.
 
Release notes: https://docs.wagtail.org/en/stable/releases/4.0.html

Be sure to review the release notes for the major versions we missed:
https://docs.wagtail.org/en/stable/releases/4.0.html

**Comment by mwvolo** [comment]
Ed is going to review changelog

**Comment by jpslav** [comment]
Before we work on this, let's chat about relative priority of this work to other work.

**Comment by erikayvonne** [comment]
@edwoodward has done all the code changes - just need to put this up on dev and test. we'll want to update this outside of a release cycle likely, so we can track any issues that arise from this upgrade versus elsewhere. 

aiming for end of June / July to start moving this forward - we may want to loop in CMs/Creative Services/other stakeholders to test (by engaging as they typically do to ensure it still functions as expected). 

FYI @openstaxalina @DominiqueShu

**Comment by openstaxalina** [comment]
Yes we would like to assist with testing - please keep us updated as to when an environment is ready to be tested! cc @theresamasciale @yblock

**Comment by DominiqueShu** [comment]
@andymuddimer will you be testing?

**Comment by erikayvonne** [comment]
tentatively aiming to get this out between 8/9 and 8/23 releases - tbc based on testing.

**Comment by erikayvonne** [comment]
may need to push this back to between 8/23 and 9/6 or further so there is enough time for the Content team to test

**Comment by erikayvonne** [comment]
@ne-newton @therealmarv hi there, any updates on CE-tech's testing for this? we'd love to get this out soon (in between our regular release cycle) so getting an update would be helpful as we can then target a date.

**Comment by erikayvonne** [comment]
thanks @therealmarv - targeting the w/o 9/25 to get this out cc @edwoodward

**Comment by erikayvonne** [comment]
updated target date is 10/10 so we do this when Michael isn't OOO.

**Comment by erikayvonne** [comment]
latest updated target date is week of 10/23 so we have Roy in office (and offset during release cycle).

**Comment by erikayvonne** [comment]
This will be released tomorrow (Wednesday 10/25) - cc @openstaxalina @DominiqueShu

**Comment by brittanyearly** [comment]
Closing as complete.
