### ISSUE TITLE
Investigate django-meta package to handle SEO/social pages in the CMS

### ISSUE THREAD

**Issue by mwvolo** [openstax/openstax-cms#1344]
Found this package that might help us with the blank HTML templates we render for search engines, twitter, facebook, etc.
https://github.com/nephila/django-meta

**Comment by edwoodward** [comment]
@mwvolo I don't think this is what we are looking for. The meta data is embedded in code and not editable by users. See [documentation](https://django-meta.readthedocs.io/en/latest/index.html)

**Comment by mwvolo** [comment]
cool - thanks for checking it out, @edwoodward!
