### ISSUE TITLE
Add page to CMS for Ally Partner Logos

### ISSUE THREAD

**Issue by mwvolo** [openstax/openstax-cms#1353]
# Description
We have been maintaining a separate subdomain web page for partners to download official OpenStax partner/ally logos.
https://staxlogos.openstax.org/
Implement that page in osweb instead.

**Comment by brittanyearly** [comment]
Created on Staging: https://staging.openstax.org/ally-logos

**Comment by brittanyearly** [comment]
Closed, created new card.
