### ISSUE TITLE
Fundraiser set as Message does not respect end date of Goal

### ISSUE THREAD

**Issue by edwoodward** [openstax/openstax-cms#1372]
### Description

The Fundraiser object has the option of being a message or a Goal. The Goal option puts a timer on the popup. If the Fundraiser is sent as a message, the Goal end date is not used to hide the popup. The Fundraiser has to be switched to a Goal to hide it. The Fundraiser either needs a new date field for the message option or the Goal date could be renamed and used for either option.

### Acceptance Test
Fundraiser popup hides when expected regardless of the option selected (Message or Goal)

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Staging, closing.
