### ISSUE TITLE
School Salesforce query is looking for fields that have been removed

### ISSUE THREAD

**Issue by edwoodward** [openstax/openstax-cms#1378]
### Description
3 testimonial fields are part of the Schools Salesforce query, but they have been removed from the Account object in Salesforce. The 2 fields are
* Testimonial__c
* Testimonial_Name__c
* Testimonial_?__c

These fields need to be removed from the query and the CMS database

### Acceptance Test
The update_schools command runs without error

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
