### ISSUE TITLE
Resource Downloads without books are causing error when trying to send to Salesforce

### ISSUE THREAD

**Issue by edwoodward** [openstax/openstax-cms#1385]
### Description
Sentry error caused when trying to send a Resource Download to Salesforce without a book. The lack of a book causes an error when trying to retrieve the Salesforce Abbreviation for the book. The fix is to not save a Resource Download that does not have a book and the check for a book before sending to Salesforce

### Acceptance Tests
Resource Downloads without a book should not be saved or send to Salesforce. This is difficult if not impossible to test since we don't know how one can be sent without a book.

**Comment by brittanyearly** [comment]
Nothing to test in Staging.

**Comment by brittanyearly** [comment]
This was released. Closing.
