### ISSUE TITLE
Upgrade to Wagtail 3.0.3

### ISSUE THREAD

**Issue by edwoodward** [openstax/openstax-cms#1399]
* Update Wagtail to 3.0.3
* Make sure Django is on 4.0.4
* Update Python to 3.10 (separate PR in deployment)

**Comment by brittanyearly** [comment]
Post deployment task: run command `python manage.py update_index`

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production. No need to run command.
