### ISSUE TITLE
Bug: K12 Resources field

### ISSUE THREAD

**Issue by dmoreno27** [openstax/openstax-cms#1426]
Original K12 flag used to feed resources into subject pages adds banners to resources on book pages. Per content team, not preferred. I removed all of those flags but few/no resources are displaying on the K12 subject pages. 

Solution: Add new field as flag to specifically display resource on K12 pages. This should avoid any conflicts with field use. 

PR: https://github.com/openstax/openstax-cms/pull/1425
Release: https://github.com/openstax/openstax-cms/releases/tag/v6.6.3
There shouldn't be any front-end edits needed.

**Comment by brittanyearly** [comment]
Verified in Production.
