### ISSUE TITLE
Request to update several people on the Team page

### ISSUE THREAD

**Issue by philschatz** [openstax/openstax-cms#1492]
There are several people that are missing on the https://openstax.org/team page. What's a good way to update that list?

/cc @openstaxalina

**Comment by edwoodward** [comment]
@philschatz Can you add a list of who is missing?

**Comment by openstaxalina** [comment]
@philschatz it is possible that those folks opted out. A form was shared awhile back (I cannot find it, unfortunately) and I understand several people opted out. 

As to the changes I wanted to request:

- [ ] @edwoodward is it possible to correct my name spelling? It is currently misspelled as "Salvik" (should be "Slavik"). 
- [ ] And could you please adjust my title to "Director of Content Development"? 
- [ ] Finally, could you please remove Jacqueline Yarbrough from the page, as she is no longer with OpenStax.

**Comment by openstaxalina** [comment]
thank you very much, @edwoodward !

**Comment by erikayvonne** [comment]
thanks all! closing this card as completed.
