### ISSUE TITLE
Upgrade to Wagtail 5.x

### ISSUE THREAD

**Issue by mwvolo** [openstax/openstax-cms#1542]
Andy and Dominique met with me asking about upgrading to Wagtail 5+, seeing some new feature that would be useful to them around image and document management. (probably [this](https://docs.wagtail.org/en/stable/releases/5.0.html#object-usage-information-on-deleting-objects))

The following release notes are related:
https://docs.wagtail.org/en/stable/releases/5.0.html
https://docs.wagtail.org/en/stable/releases/5.1.html
https://docs.wagtail.org/en/stable/releases/5.2.html

This will likely encompass moving to 5.2, as it is a LTS release (receives support for at least 12 months).

Not related but barring a better place to put these, notes from the conversation with AM/DS on 12/18)
- Wagtail upgrade (Michael will attempt but is unable to promise by Q1; will work with Marvin and team on future upgrade plans)
- Content cleanup (mostly manual - consult with Content team on naming convention)
- Dynamic page content — work up a plan and talk with Roy
- Website search (across REX and OSWeb)
- Possible high-priority request: India-specific sponsorship of pages, possible need to target ads based on user location
- If user location becomes available, target Amazon ads based on it.

**Comment by erikayvonne** [comment]
this can go on qa first w/o January 22 - and then on dev after Roy is done with 1/24 release
aiming for upgrade to be between February 6 and 21 releases (accounts release takes priority over this)
cc @mwvolo @brittanyearly

**Comment by erikayvonne** [comment]
@yblock to check this out on QA before it goes on dev

targeting w/o Feb 12, unless accounts release spills over

**Comment by yblock** [comment]
The only thing I see that isn't working is the "usage count" feature on documents to show where and how often a document is used. Not sure if that's expected to be working but it would be nice. 

<img width="206" alt="Screenshot 2024-01-23 at 11 00 26 AM" src="https://github.com/openstax/openstax-cms/assets/5865292/c7b92bbc-f061-4004-894c-915b65c8ca0f">

**Comment by mwvolo** [comment]
@yblock Is this a regression or it never worked?

**Comment by yblock** [comment]
Regression, it only started working recently and is currently working on prod.

**Comment by mwvolo** [comment]
I changed the A&P book cover on the book, which updated the usage to 1.
I think it might be that the documents you looked at were actually not in use?


![Image](https://github.com/openstax/openstax-cms/assets/3905516/8eefb4b1-4440-43ce-935e-af4b1b9ea426)

**Comment by yblock** [comment]
I checked many, and confirmed in the same way you did that it wasn't working. But, checking now it looks like it is working. Maybe a caching issue on my end or indexing taking time, I don't know. But it looks good now! 👍
