### ISSUE TITLE
Make sure page ids are static for all relevant cases (adding and deleting a page, etc). 

### ISSUE THREAD

**Issue by rich-hart** [openstax/openstax-cms#74]

**Comment by mwharrison** [comment]
Do you have a suggestion on how we implement this?

**Comment by rich-hart** [comment]
Actually, I think that it's already implemented.    I was worried about the case of where an ``editor`` creates a page, deletes it, then creates it again.  Which would cause fields like ``id`` to change.  But i forgot that the ``editors`` group allows users to change pages while restricting them from being deleted.  So in the way the site is currently designed, id should remain static unless an admin decides to delete a page for some reason.

**Comment by mwharrison** [comment]
Hmm, I don't think Editors are restricted from deleting pages - or at least that has not been specified yet. I agree that these ID's will not change once the page is created -unless it is deleted (obviously).
I think what Dak wanted initially, was us to replace the IDs with the slug name of the page, which might be a possibility. Either option does not restrict people from breaking things if they do things they shouldn't. We can keep this open until we hear more from the frontend people on how big of an issue this is.

**Comment by rich-hart** [comment]
ok....   Btw, here are the default ``editor`` permissions just in case it's relevant later. 
![editor_permissions](https://cloud.githubusercontent.com/assets/2857670/13151348/61f71cf2-d62f-11e5-98e0-e71e100733da.png)

**Comment by rich-hart** [comment]
Ok, just to repost what I talked about with @mwharrison.   These settings are misleading.  The site is currently configured to let editors have permissions to change all content on the site, that includes deleting pages.  Editors can be restricted from deleting pages but it wouldn't make sense given we'll only have 1 editor managing all the content for the foreseeable future,

**Comment by mwharrison** [comment]
The reason for the discrepancy is the decision to create groups that correspond to Openstax needs. We don't have enough people to have an editor and a moderator role, so it has been requested that the Editor role inherit all the moderator permissions - including deleting content.
