### ISSUE TITLE
Blog summary data should include first chunk of body

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/openstax-cms#779]
The CMS data for the summary of blog articles does not include any of the body, so to make all the blurbs, the FE has to pull the article data for every article. The blurb comes from the first chunk of body data. If that data were included in the summary, we could save a lot of calls.

The alt text for the featured image should be in the summary info, too, but I think you may have done that with a recent PR.

##Acceptance

blog page summaries can be constructed without having to pull the individual article pages

**Comment by mwharrison** [comment]
@RoyEJohnson, what are you using to truncate the text? A certain number of words, characters, etc.?

**Comment by RoyEJohnson** [comment]
I pull the first paragraph and use CSS to restrict it to the space I have. You don't need to parse it; that's easy enough for me.

**Comment by RoyEJohnson** [comment]
But I suppose if you have a straightforward way to extract the first chunk inside `<p>` tags, that would be that much better.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
