### ISSUE TITLE
Blog search results should include publish dates

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/openstax-cms#838]
Blog search results should have the same structure as the `articles` returned from `api/news`. They are missing the `date` field in particular, and also `article_image_alt`.

**Comment by Brooke-Fail** [comment]
Blog search code is hidden for the 8/28 release.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
