### ISSUE TITLE
Duplicate line

### ISSUE THREAD

**Issue by yblock** [openstax/openstax-cms#896]
https://github.com/openstax/openstax-cms/blob/4c5e65d526db3ca2d4b69545160af2cea1bb54b0/oxauth/functions.py#L47

This line of code is repeated 3 lines below.

**Comment by mwharrison** [comment]
@yblock - I'm assigning this to you since you know how to fix it! :)

**Comment by Brooke-Fail** [comment]
Verified in QA with sha 66e2fd16059b30c689b2c445022eb16c97d9aa14.

**Comment by Brooke-Fail** [comment]
Verified in Production.
