### ISSUE TITLE
API for collaborators?

### ISSUE THREAD

**Issue by droza0** [openstax/openstax-cms#900]
Hi Openstax team, 

I'm working on a team that's looking to use OpenStax content to create curricular modules that are adaptive and whose impact is measurable. We were wondering about whether the API for the CMS is available to third parties looking to use OpenStax data in this way, or alternatively, what the policy is on webscraping?

Thank you!

**Comment by allisonhowell** [comment]
Allison following up on this.

**Comment by droza0** [comment]
Thanks Allison! Looking forward to hearing back!

**Comment by allisonhowell** [comment]
@droza0 Can you tell me what team you're working with?

**Comment by droza0** [comment]
Hi Allison, I'm working with the team over at Sagefy: https://github.com/sagefy

**Comment by mwharrison** [comment]
Here is something we came up with to describe using our API by external parties. Hopefully, this answers your question!
[API Policy](https://app.zenhub.com/files/45121064/fe472026-6118-40e3-8517-eff535e94e77/download)
